### ISSUE TITLE
Instructions unclear

### ISSUE THREAD

**Issue by WhyNotHugo** [maxvoltar/photo-stream#59]
I've been trying to get this set up, but the instructions seem quite unclear/incomplete (at least to me, since I'm not a ruby developer).

After cloning the repository, running either `gem install` or `bundle install` attempt to alter the OS installation and prompt for sudo permissions. Of course, I refused this, but figuring out how to set this up without giving it unlimited access still took some figuring out.

The following needs to be run in order for bundler to be able to install the dependencies without messing up the OS installation:

    bundle config set path 'vendor/bundle'

There's a step in the docs regarding `xcode`, but that seems to be a macOS-only thing, so I wasn't able to run that. I did, however, have to install `libvips`, which was readily available for my distribution.

Finally, the right way of running this is using:

    bundle exec jekyll serve

I guess you might have something set up so as not to need this, but generally I think others will.
Finally though, the I'm getting this error, and I've no idea how to proceed or work around it:

```
➜ bundle exec jekyll serve
Configuration file: /home/hugo/workspace/Hugo/photos/photo-stream/_config.yml
            Source: /home/hugo/workspace/Hugo/photos/photo-stream
       Destination: /home/hugo/workspace/Hugo/photos/photo-stream/_site
 Incremental build: disabled. Enable with --incremental
      Generating... 
/home/hugo/workspace/Hugo/photos/photo-stream/vendor/bundle/ruby/2.7.0/gems/jekyll-4.0.0/lib/jekyll/convertible.rb:41: warning: Using the last argument as keyword parameters is deprecated
/home/hugo/workspace/Hugo/photos/photo-stream/vendor/bundle/ruby/2.7.0/gems/jekyll-4.0.0/lib/jekyll/convertible.rb:41: warning: Using the last argument as keyword parameters is deprecated
/home/hugo/workspace/Hugo/photos/photo-stream/vendor/bundle/ruby/2.7.0/gems/jekyll-4.0.0/lib/jekyll/convertible.rb:41: warning: Using the last argument as keyword parameters is deprecated
/home/hugo/workspace/Hugo/photos/photo-stream/vendor/bundle/ruby/2.7.0/gems/jekyll-4.0.0/lib/jekyll/convertible.rb:41: warning: Using the last argument as keyword parameters is deprecated
/home/hugo/workspace/Hugo/photos/photo-stream/vendor/bundle/ruby/2.7.0/gems/jekyll-4.0.0/lib/jekyll/convertible.rb:41: warning: Using the last argument as keyword parameters is deprecated
/home/hugo/workspace/Hugo/photos/photo-stream/vendor/bundle/ruby/2.7.0/gems/jekyll-4.0.0/lib/jekyll/convertible.rb:41: warning: Using the last argument as keyword parameters is deprecated
/home/hugo/workspace/Hugo/photos/photo-stream/vendor/bundle/ruby/2.7.0/gems/jekyll-4.0.0/lib/jekyll/convertible.rb:41: warning: Using the last argument as keyword parameters is deprecated
/home/hugo/workspace/Hugo/photos/photo-stream/vendor/bundle/ruby/2.7.0/gems/jekyll-4.0.0/lib/jekyll/convertible.rb:41: warning: Using the last argument as keyword parameters is deprecated
/home/hugo/workspace/Hugo/photos/photo-stream/vendor/bundle/ruby/2.7.0/gems/jekyll-4.0.0/lib/jekyll/convertible.rb:41: warning: Using the last argument as keyword parameters is deprecated
/home/hugo/workspace/Hugo/photos/photo-stream/vendor/bundle/ruby/2.7.0/gems/jekyll-4.0.0/lib/jekyll/convertible.rb:41: warning: Using the last argument as keyword parameters is deprecated
/home/hugo/workspace/Hugo/photos/photo-stream/vendor/bundle/ruby/2.7.0/gems/jekyll-4.0.0/lib/jekyll/convertible.rb:41: warning: Using the last argument as keyword parameters is deprecated
/home/hugo/workspace/Hugo/photos/photo-stream/vendor/bundle/ruby/2.7.0/gems/jekyll-4.0.0/lib/jekyll/convertible.rb:41: warning: Using the last argument as keyword parameters is deprecated
/home/hugo/workspace/Hugo/photos/photo-stream/vendor/bundle/ruby/2.7.0/gems/jekyll-4.0.0/lib/jekyll/convertible.rb:41: warning: Using the last argument as keyword parameters is deprecated
/home/hugo/workspace/Hugo/photos/photo-stream/vendor/bundle/ruby/2.7.0/gems/jekyll-4.0.0/lib/jekyll/convertible.rb:41: warning: Using the last argument as keyword parameters is deprecated
/home/hugo/workspace/Hugo/photos/photo-stream/vendor/bundle/ruby/2.7.0/gems/jekyll-4.0.0/lib/jekyll/convertible.rb:41: warning: Using the last argument as keyword parameters is deprecated
/home/hugo/workspace/Hugo/photos/photo-stream/vendor/bundle/ruby/2.7.0/gems/jekyll-4.0.0/lib/jekyll/convertible.rb:41: warning: Using the last argument as keyword parameters is deprecated
/home/hugo/workspace/Hugo/photos/photo-stream/vendor/bundle/ruby/2.7.0/gems/jekyll-4.0.0/lib/jekyll/tags/include.rb:179: warning: Using the last argument as keyword parameters is deprecated
/home/hugo/workspace/Hugo/photos/photo-stream/vendor/bundle/ruby/2.7.0/gems/jekyll-4.0.0/lib/jekyll/tags/include.rb:179: warning: Using the last argument as keyword parameters is deprecated
  Liquid Exception: no start of image marker found in feed.xml
                    ------------------------------------------------
      Jekyll 4.0.0   Please append `--trace` to the `serve` command 
                     for any additional information or backtrace. 
                    ------------------------------------------------
Traceback (most recent call last):
	67: from /usr/bin/bundle:23:in `<main>'
	66: from /usr/bin/bundle:23:in `load'
	65: from /home/hugo/.gem/ruby/2.7.0/gems/bundler-2.1.4/exe/bundle:34:in `<top (required)>'
	64: from /home/hugo/.gem/ruby/2.7.0/gems/bundler-2.1.4/lib/bundler/friendly_errors.rb:123:in `with_friendly_errors'
	63: from /home/hugo/.gem/ruby/2.7.0/gems/bundler-2.1.4/exe/bundle:46:in `block in <top (required)>'
	62: from /home/hugo/.gem/ruby/2.7.0/gems/bundler-2.1.4/lib/bundler/cli.rb:24:in `start'
	61: from /home/hugo/.gem/ruby/2.7.0/gems/bundler-2.1.4/lib/bundler/vendor/thor/lib/thor/base.rb:476:in `start'
	60: from /home/hugo/.gem/ruby/2.7.0/gems/bundler-2.1.4/lib/bundler/cli.rb:30:in `dispatch'
	59: from /home/hugo/.gem/ruby/2.7.0/gems/bundler-2.1.4/lib/bundler/vendor/thor/lib/thor.rb:399:in `dispatch'
	58: from /home/hugo/.gem/ruby/2.7.0/gems/bundler-2.1.4/lib/bundler/vendor/thor/lib/thor/invocation.rb:127:in `invoke_command'
	57: from /home/hugo/.gem/ruby/2.7.0/gems/bundler-2.1.4/lib/bundler/vendor/thor/lib/thor/command.rb:27:in `run'
	56: from /home/hugo/.gem/ruby/2.7.0/gems/bundler-2.1.4/lib/bundler/cli.rb:476:in `exec'
	55: from /home/hugo/.gem/ruby/2.7.0/gems/bundler-2.1.4/lib/bundler/cli/exec.rb:28:in `run'
	54: from /home/hugo/.gem/ruby/2.7.0/gems/bundler-2.1.4/lib/bundler/cli/exec.rb:63:in `kernel_load'
	53: from /home/hugo/.gem/ruby/2.7.0/gems/bundler-2.1.4/lib/bundler/cli/exec.rb:63:in `load'
	52: from /home/hugo/workspace/Hugo/photos/photo-stream/vendor/bundle/ruby/2.7.0/bin/jekyll:23:in `<top (required)>'
	51: from /home/hugo/workspace/Hugo/photos/photo-stream/vendor/bundle/ruby/2.7.0/bin/jekyll:23:in `load'
	50: from /home/hugo/workspace/Hugo/photos/photo-stream/vendor/bundle/ruby/2.7.0/gems/jekyll-4.0.0/exe/jekyll:15:in `<top (required)>'
	49: from /home/hugo/workspace/Hugo/photos/photo-stream/vendor/bundle/ruby/2.7.0/gems/mercenary-0.3.6/lib/mercenary.rb:19:in `program'
	48: from /home/hugo/workspace/Hugo/photos/photo-stream/vendor/bundle/ruby/2.7.0/gems/mercenary-0.3.6/lib/mercenary/program.rb:42:in `go'
	47: from /home/hugo/workspace/Hugo/photos/photo-stream/vendor/bundle/ruby/2.7.0/gems/mercenary-0.3.6/lib/mercenary/command.rb:220:in `execute'
	46: from /home/hugo/workspace/Hugo/photos/photo-stream/vendor/bundle/ruby/2.7.0/gems/mercenary-0.3.6/lib/mercenary/command.rb:220:in `each'
	45: from /home/hugo/workspace/Hugo/photos/photo-stream/vendor/bundle/ruby/2.7.0/gems/mercenary-0.3.6/lib/mercenary/command.rb:220:in `block in execute'
	44: from /home/hugo/workspace/Hugo/photos/photo-stream/vendor/bundle/ruby/2.7.0/gems/jekyll-4.0.0/lib/jekyll/commands/serve.rb:86:in `block (2 levels) in init_with_program'
	43: from /home/hugo/workspace/Hugo/photos/photo-stream/vendor/bundle/ruby/2.7.0/gems/jekyll-4.0.0/lib/jekyll/command.rb:89:in `process_with_graceful_fail'
	42: from /home/hugo/workspace/Hugo/photos/photo-stream/vendor/bundle/ruby/2.7.0/gems/jekyll-4.0.0/lib/jekyll/command.rb:89:in `each'
	41: from /home/hugo/workspace/Hugo/photos/photo-stream/vendor/bundle/ruby/2.7.0/gems/jekyll-4.0.0/lib/jekyll/command.rb:89:in `block in process_with_graceful_fail'
	40: from /home/hugo/workspace/Hugo/photos/photo-stream/vendor/bundle/ruby/2.7.0/gems/jekyll-4.0.0/lib/jekyll/commands/build.rb:36:in `process'
	39: from /home/hugo/workspace/Hugo/photos/photo-stream/vendor/bundle/ruby/2.7.0/gems/jekyll-4.0.0/lib/jekyll/commands/build.rb:65:in `build'
	38: from /home/hugo/workspace/Hugo/photos/photo-stream/vendor/bundle/ruby/2.7.0/gems/jekyll-4.0.0/lib/jekyll/command.rb:28:in `process_site'
	37: from /home/hugo/workspace/Hugo/photos/photo-stream/vendor/bundle/ruby/2.7.0/gems/jekyll-4.0.0/lib/jekyll/site.rb:76:in `process'
	36: from /home/hugo/workspace/Hugo/photos/photo-stream/vendor/bundle/ruby/2.7.0/gems/jekyll-4.0.0/lib/jekyll/site.rb:202:in `render'
	35: from /home/hugo/workspace/Hugo/photos/photo-stream/vendor/bundle/ruby/2.7.0/gems/jekyll-4.0.0/lib/jekyll/site.rb:515:in `render_pages'
	34: from /home/hugo/workspace/Hugo/photos/photo-stream/vendor/bundle/ruby/2.7.0/gems/jekyll-4.0.0/lib/jekyll/site.rb:515:in `each'
	33: from /home/hugo/workspace/Hugo/photos/photo-stream/vendor/bundle/ruby/2.7.0/gems/jekyll-4.0.0/lib/jekyll/site.rb:516:in `block in render_pages'
	32: from /home/hugo/workspace/Hugo/photos/photo-stream/vendor/bundle/ruby/2.7.0/gems/jekyll-4.0.0/lib/jekyll/site.rb:523:in `render_regenerated'
	31: from /home/hugo/workspace/Hugo/photos/photo-stream/vendor/bundle/ruby/2.7.0/gems/jekyll-4.0.0/lib/jekyll/renderer.rb:63:in `run'
	30: from /home/hugo/workspace/Hugo/photos/photo-stream/vendor/bundle/ruby/2.7.0/gems/jekyll-4.0.0/lib/jekyll/renderer.rb:80:in `render_document'
	29: from /home/hugo/workspace/Hugo/photos/photo-stream/vendor/bundle/ruby/2.7.0/gems/jekyll-4.0.0/lib/jekyll/renderer.rb:127:in `render_liquid'
	28: from /home/hugo/workspace/Hugo/photos/photo-stream/vendor/bundle/ruby/2.7.0/gems/jekyll-4.0.0/lib/jekyll/liquid_renderer/file.rb:32:in `render!'
	27: from /home/hugo/workspace/Hugo/photos/photo-stream/vendor/bundle/ruby/2.7.0/gems/jekyll-4.0.0/lib/jekyll/liquid_renderer/file.rb:60:in `measure_time'
	26: from /home/hugo/workspace/Hugo/photos/photo-stream/vendor/bundle/ruby/2.7.0/gems/jekyll-4.0.0/lib/jekyll/liquid_renderer/file.rb:33:in `block in render!'
	25: from /home/hugo/workspace/Hugo/photos/photo-stream/vendor/bundle/ruby/2.7.0/gems/jekyll-4.0.0/lib/jekyll/liquid_renderer/file.rb:53:in `measure_bytes'
	24: from /home/hugo/workspace/Hugo/photos/photo-stream/vendor/bundle/ruby/2.7.0/gems/jekyll-4.0.0/lib/jekyll/liquid_renderer/file.rb:34:in `block (2 levels) in render!'
	23: from /home/hugo/workspace/Hugo/photos/photo-stream/vendor/bundle/ruby/2.7.0/gems/jekyll-4.0.0/lib/jekyll/liquid_renderer/file.rb:49:in `measure_counts'
	22: from /home/hugo/workspace/Hugo/photos/photo-stream/vendor/bundle/ruby/2.7.0/gems/jekyll-4.0.0/lib/jekyll/liquid_renderer/file.rb:35:in `block (3 levels) in render!'
	21: from /home/hugo/workspace/Hugo/photos/photo-stream/vendor/bundle/ruby/2.7.0/gems/liquid-4.0.3/lib/liquid/template.rb:220:in `render!'
	20: from /home/hugo/workspace/Hugo/photos/photo-stream/vendor/bundle/ruby/2.7.0/gems/liquid-4.0.3/lib/liquid/template.rb:207:in `render'
	19: from /home/hugo/workspace/Hugo/photos/photo-stream/vendor/bundle/ruby/2.7.0/gems/liquid-4.0.3/lib/liquid/template.rb:242:in `with_profiling'
	18: from /home/hugo/workspace/Hugo/photos/photo-stream/vendor/bundle/ruby/2.7.0/gems/liquid-4.0.3/lib/liquid/template.rb:208:in `block in render'
	17: from /home/hugo/workspace/Hugo/photos/photo-stream/vendor/bundle/ruby/2.7.0/gems/liquid-4.0.3/lib/liquid/block_body.rb:91:in `render'
	16: from /home/hugo/workspace/Hugo/photos/photo-stream/vendor/bundle/ruby/2.7.0/gems/liquid-4.0.3/lib/liquid/block_body.rb:103:in `render_node_to_output'
	15: from /home/hugo/workspace/Hugo/photos/photo-stream/vendor/bundle/ruby/2.7.0/gems/liquid-4.0.3/lib/liquid/tags/assign.rb:26:in `render'
	14: from /home/hugo/workspace/Hugo/photos/photo-stream/vendor/bundle/ruby/2.7.0/gems/liquid-4.0.3/lib/liquid/variable.rb:82:in `render'
	13: from /home/hugo/workspace/Hugo/photos/photo-stream/vendor/bundle/ruby/2.7.0/gems/liquid-4.0.3/lib/liquid/variable.rb:82:in `inject'
	12: from /home/hugo/workspace/Hugo/photos/photo-stream/vendor/bundle/ruby/2.7.0/gems/liquid-4.0.3/lib/liquid/variable.rb:82:in `each'
	11: from /home/hugo/workspace/Hugo/photos/photo-stream/vendor/bundle/ruby/2.7.0/gems/liquid-4.0.3/lib/liquid/variable.rb:84:in `block in render'
	10: from /home/hugo/workspace/Hugo/photos/photo-stream/vendor/bundle/ruby/2.7.0/gems/liquid-4.0.3/lib/liquid/context.rb:86:in `invoke'
	 9: from /home/hugo/workspace/Hugo/photos/photo-stream/vendor/bundle/ruby/2.7.0/gems/liquid-4.0.3/lib/liquid/strainer.rb:56:in `invoke'
	 8: from /home/hugo/workspace/Hugo/photos/photo-stream/_plugins/photo_filter.rb:7:in `photo_filter'
	 7: from /home/hugo/workspace/Hugo/photos/photo-stream/_plugins/photo_filter.rb:7:in `sort_by'
	 6: from /home/hugo/workspace/Hugo/photos/photo-stream/_plugins/photo_filter.rb:7:in `each'
	 5: from /home/hugo/workspace/Hugo/photos/photo-stream/_plugins/photo_filter.rb:8:in `block in photo_filter'
	 4: from /home/hugo/workspace/Hugo/photos/photo-stream/_plugins/photo_filter.rb:8:in `new'
	 3: from /home/hugo/workspace/Hugo/photos/photo-stream/vendor/bundle/ruby/2.7.0/gems/exifr-1.3.6/lib/exifr/jpeg.rb:34:in `initialize'
	 2: from /home/hugo/workspace/Hugo/photos/photo-stream/vendor/bundle/ruby/2.7.0/gems/exifr-1.3.6/lib/exifr/jpeg.rb:34:in `open'
	 1: from /home/hugo/workspace/Hugo/photos/photo-stream/vendor/bundle/ruby/2.7.0/gems/exifr-1.3.6/lib/exifr/jpeg.rb:34:in `block in initialize'
/home/hugo/workspace/Hugo/photos/photo-stream/vendor/bundle/ruby/2.7.0/gems/exifr-1.3.6/lib/exifr/jpeg.rb:102:in `examine': no start of image marker found (EXIFR::MalformedJPEG)
```

All the jpegs in my `photos/originals` directories seem to have valid EXIF data, so I'm not sure what's up around there.

Am I missing some steps? Can we maybe add the above clarifications to the README?

**Comment by northcott-j** [comment]
I ran into a similar issue. I had to import the photo into Lightroom and re-export it. I found out which photo it was by putting `puts photo.path` above [this line](https://github.com/maxvoltar/photo-stream/blob/1356443a70ba7ae90bcf2f2bb0846af815629a74/_plugins/photo_filter.rb#L8)

**Comment by WhyNotHugo** [comment]
Huh, turns out all the photos need to be `jpeg`s, so re-encoding them that fixed that.
Still think the above mentions can be included in the README, thoughts?

**Comment by maxvoltar** [comment]
@WhyNotHugo hey there, this is the first time I'm putting a project this complex out in the open. I'm sorry the documentation isn't super solid, even though a handful of people already worked on it. 

Mind opening up a PR for what you think we should add to them?

**Comment by WhyNotHugo** [comment]
No need to apologise here, I really appreciate the work you've done around here. Sure, lemme get the wording quite right, and I'll send a PR. :)
