### ISSUE TITLE
 Liquid Exception: no start of image marker found in feed.xml 

### ISSUE THREAD

**Issue by luffythink** [maxvoltar/photo-stream#82]
**声明：仔细看过已提交过的issue和Google搜索过相关问题后依然没有找到答案，所以才发了一个新的 issue。**

## 问题类型
Bug Report

## 相关信息
Mac 10.15.3 
[photo-stream](https://github.com/maxvoltar/photo-stream)能在本地成功运行

## 问题重现

` Liquid Exception: no start of image marker found in feed.xml `

<img width="509" alt="jietu" src="https://user-images.githubusercontent.com/40992395/88991248-c703ab80-d312-11ea-8e1d-6b47463f5e2d.png">

在向photos/original文件夹添加新的照片，执行`bundle exec jekyll build`时报错，报错信息如下：

```bash
EXIFR::MalformedJPEG: no start of image marker found
  /Users/luffythink/Documents/photossteam/vendor/bundle/ruby/2.6.0/gems/exifr-1.3.6/lib/exifr/jpeg.rb:102:in `examine'
  /Users/luffythink/Documents/photossteam/vendor/bundle/ruby/2.6.0/gems/exifr-1.3.6/lib/exifr/jpeg.rb:34:in `block in initialize'
  /Users/luffythink/Documents/photos/vendor/bundle/ruby/2.6.0/gems/exifr-1.3.6/lib/exifr/jpeg.rb:34:in `open'
  /Users/luffythink/Documents/photossteam/vendor/bundle/ruby/2.6.0/gems/exifr-1.3.6/lib/exifr/jpeg.rb:34:in `initialize'
  /Users/luffythink/Documents/photossteam/_plugins/photo_filter.rb:8:in `new'
  /Users/luffythink/Documents/photossteam/_plugins/photo_filter.rb:8:in `block in photo_filter'
  /Users/luffythink/Documents/photossteam/_plugins/photo_filter.rb:7:in `each'
  /Users/luffythink/Documents/photossteam/_plugins/photo_filter.rb:7:in `sort_by'
  /Users/luffythink/Documents/photossteam/_plugins/photo_filter.rb:7:in `photo_filter'
  /Users/luffythink/Documents/photossteam/vendor/bundle/ruby/2.6.0/gems/liquid-4.0.3/lib/liquid/strainer.rb:56:in `invoke'
  /Users/luffythink/Documents/photossteam/vendor/bundle/ruby/2.6.0/gems/liquid-4.0.3/lib/liquid/context.rb:86:in `invoke'
  /Users/luffythink/Documents/photossteam/vendor/bundle/ruby/2.6.0/gems/liquid-4.0.3/lib/liquid/variable.rb:84:in `block in render'
  /Users/luffythink/Documents/photossteam/vendor/bundle/ruby/2.6.0/gems/liquid-4.0.3/lib/liquid/variable.rb:82:in `each'
  /Users/luffythink/Documents/photossteam/vendor/bundle/ruby/2.6.0/gems/liquid-4.0.3/lib/liquid/variable.rb:82:in `inject'
  /Users/luffythink/Documents/photossteam/vendor/bundle/ruby/2.6.0/gems/liquid-4.0.3/lib/liquid/variable.rb:82:in `render'
  /Users/luffythink/Documents/photossteam/vendor/bundle/ruby/2.6.0/gems/liquid-4.0.3/lib/liquid/tags/assign.rb:26:in `render'
  /Users/luffythink/Documents/photossteam/vendor/bundle/ruby/2.6.0/gems/liquid-4.0.3/lib/liquid/block_body.rb:103:in `render_node_to_output'
  /Users/luffythink/Documents/photossteam/vendor/bundle/ruby/2.6.0/gems/liquid-4.0.3/lib/liquid/block_body.rb:91:in `render'
  /Users/luffythink/Documents/photossteam/vendor/bundle/ruby/2.6.0/gems/liquid-4.0.3/lib/liquid/template.rb:208:in `block in render'
  /Users/luffythink/Documents/photossteam/vendor/bundle/ruby/2.6.0/gems/liquid-4.0.3/lib/liquid/template.rb:242:in `with_profiling'
  /Users/luffythink/Documents/photossteam/vendor/bundle/ruby/2.6.0/gems/liquid-4.0.3/lib/liquid/template.rb:207:in `render'
  /Users/luffythink/Documents/photossteam/vendor/bundle/ruby/2.6.0/gems/liquid-4.0.3/lib/liquid/template.rb:220:in `render!'
  /Users/luffythink/Documents/photossteam/vendor/bundle/ruby/2.6.0/gems/jekyll-4.0.1/lib/jekyll/liquid_renderer/file.rb:39:in `block (3 levels) in render!'
  /Users/luffythink/Documents/photossteam/vendor/bundle/ruby/2.6.0/gems/jekyll-4.0.1/lib/jekyll/liquid_renderer/file.rb:59:in `measure_counts'
  /Users/luffythink/Documents/photossteam/vendor/bundle/ruby/2.6.0/gems/jekyll-4.0.1/lib/jekyll/liquid_renderer/file.rb:38:in `block (2 levels) in render!'
  /Users/luffythink/Documents/photossteam/vendor/bundle/ruby/2.6.0/gems/jekyll-4.0.1/lib/jekyll/liquid_renderer/file.rb:63:in `measure_bytes'
  /Users/luffythink/Documents/photossteam/vendor/bundle/ruby/2.6.0/gems/jekyll-4.0.1/lib/jekyll/liquid_renderer/file.rb:37:in `block in render!'
  /Users/luffythink/Documents/photossteam/vendor/bundle/ruby/2.6.0/gems/jekyll-4.0.1/lib/jekyll/liquid_renderer/file.rb:70:in `measure_time'
  /Users/luffythink/Documents/photossteam/vendor/bundle/ruby/2.6.0/gems/jekyll-4.0.1/lib/jekyll/liquid_renderer/file.rb:36:in `render!'
  /Users/luffythink/Documents/photossteam/vendor/bundle/ruby/2.6.0/gems/jekyll-4.0.1/lib/jekyll/renderer.rb:127:in `render_liquid'
  /Users/luffythink/Documents/photossteam/vendor/bundle/ruby/2.6.0/gems/jekyll-4.0.1/lib/jekyll/renderer.rb:80:in `render_document'
  /Users/luffythink/Documents/photossteam/vendor/bundle/ruby/2.6.0/gems/jekyll-4.0.1/lib/jekyll/renderer.rb:63:in `run'
  /Users/luffythink/Documents/photossteam/vendor/bundle/ruby/2.6.0/gems/jekyll-4.0.1/lib/jekyll/site.rb:523:in `render_regenerated'
  /Users/luffythink/Documents/photossteam/vendor/bundle/ruby/2.6.0/gems/jekyll-4.0.1/lib/jekyll/site.rb:516:in `block in render_pages'
  /Users/luffythink/Documents/photossteam/vendor/bundle/ruby/2.6.0/gems/jekyll-4.0.1/lib/jekyll/site.rb:515:in `each'
  /Users/luffythink/Documents/photossteam/vendor/bundle/ruby/2.6.0/gems/jekyll-4.0.1/lib/jekyll/site.rb:515:in `render_pages'
  /Users/luffythink/Documents/photossteam/vendor/bundle/ruby/2.6.0/gems/jekyll-4.0.1/lib/jekyll/site.rb:202:in `render'
  /Users/luffythink/Documents/photossteam/vendor/bundle/ruby/2.6.0/gems/jekyll-4.0.1/lib/jekyll/site.rb:76:in `process'
  /Users/luffythink/Documents/photossteam/vendor/bundle/ruby/2.6.0/gems/jekyll-4.0.1/lib/jekyll/command.rb:28:in `process_site'
  /Users/luffythink/Documents/photossteam/vendor/bundle/ruby/2.6.0/gems/jekyll-4.0.1/lib/jekyll/commands/build.rb:65:in `build'
  /Users/luffythink/Documents/photossteam/vendor/bundle/ruby/2.6.0/gems/jekyll-4.0.1/lib/jekyll/commands/build.rb:36:in `process'
  /Users/luffythink/Documents/photossteam/vendor/bundle/ruby/2.6.0/gems/jekyll-4.0.1/lib/jekyll/command.rb:89:in `block in process_with_graceful_fail'
  /Users/luffythink/Documents/photossteam/vendor/bundle/ruby/2.6.0/gems/jekyll-4.0.1/lib/jekyll/command.rb:89:in `each'
  /Users/luffythink/Documents/photossteam/vendor/bundle/ruby/2.6.0/gems/jekyll-4.0.1/lib/jekyll/command.rb:89:in `process_with_graceful_fail'
  /Users/luffythink/Documents/photossteam/vendor/bundle/ruby/2.6.0/gems/jekyll-4.0.1/lib/jekyll/commands/build.rb:18:in `block (2 levels) in init_with_program'
  /Users/luffythink/Documents/photossteam/vendor/bundle/ruby/2.6.0/gems/mercenary-0.3.6/lib/mercenary/command.rb:220:in `block in execute'
  /Users/luffythink/Documents/photossteam/vendor/bundle/ruby/2.6.0/gems/mercenary-0.3.6/lib/mercenary/command.rb:220:in `each'
  /Users/luffythink/Documents/photossteam/vendor/bundle/ruby/2.6.0/gems/mercenary-0.3.6/lib/mercenary/command.rb:220:in `execute'
  /Users/luffythink/Documents/photossteam/vendor/bundle/ruby/2.6.0/gems/mercenary-0.3.6/lib/mercenary/program.rb:42:in `go'
  /Users/luffythink/Documents/photossteam/vendor/bundle/ruby/2.6.0/gems/mercenary-0.3.6/lib/mercenary.rb:19:in `program'
  /Users/luffythink/Documents/photossteam/vendor/bundle/ruby/2.6.0/gems/jekyll-4.0.1/exe/jekyll:15:in `<top (required)>'
  /Users/luffythink/Documents/photossteam/vendor/bundle/ruby/2.6.0/bin/Jekyll:23:in `load'
  /Users/luffythink/Documents/photossteam/vendor/bundle/ruby/2.6.0/bin/Jekyll:23:in `<top (required)>'
```

起初以为是`bundle install`更新的问题，但偶然发现是添加照片里其中一张`xxx.png`格式的图片造成的这个报错，这张照片没有Exif信息。删掉这张图片就能成功build了。

**很奇怪的是**：我换了其它没有Exif信息的xxx.png格式的图片，又能成功build。因为这个报错，Google了很多信息，学习了不少关于bundle的知识，但仍然没有找到这张照片引起报错的原因，所以在这里向你们反馈这个错误信息。如有描述不妥请见谅：）

## 最后
再次感谢photo-stream团队，感谢你们提供了这样一个非常棒的照片展示工具。
PS：额外请教一下，这个photo-stream在展示图片的时候能否自动显示拍摄时间和一些可以选择的Exif信息？突然的一个idea。

**Comment by luffythink** [comment]
[](url)

**Comment by elibenton** [comment]
Did you export your photos directly from Photos on Mac?

**Comment by luffythink** [comment]
> Did you export your photos directly from Photos on Mac?
Some photos directly from Mac, and some from iPhone or Fusi-camera.Only few photos weren’t correctly recognized. I checked these photos and found no difference...Did you have a good idea?
